[package]
name = "pfile"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
fastrand = { version = "2.1.1", default-features = false, features = ["alloc"] }
sha2 = "0.10.8"
